import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          variables: {
            colorText: "#fff",
            colorInputBackground: "#252a41",
            colorPrimary: "#0E78F9",
            colorInputText: "#fff",
            colorBackground: "#1C1F2E",
          },
          layout: {
            socialButtonsVariant: "iconButton",
            logoImageUrl: "/icons/logo_flowmeet.svg",
          },
        }}
      >
        <body className={`${inter.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
